CREATE TABLE [dbo].[Theatre]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
	[TotalSeats] INT NOT NULL,
	[LocationId] INT NOT NULL,
	CONSTRAINT [CK_THEATRE_TOTALSEATS] CHECK([TotalSeats] > 0),
	CONSTRAINT [FK_THEATRE_LOCATIONID] FOREIGN KEY ([LocationId]) REFERENCES [Location]([Id])
)
